# Generated by Django 6.0.7 on 2026-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orcamentomensal_usuario_transacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Compras', 'Compras'), ('Salário', 'Salário'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
    ]
