# Generated by Django 6.0.7 on 2026-08-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='transacao_id_externo',
            field=models.CharField(blank=True, help_text='ID único da transação importada via OFX (FITID)', max_length=255, null=True, unique=True),
        ),
    ]
