# Generated by Django 6.0.7 on 2026-08-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transacao_transacao_id_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_arquivo', models.CharField(max_length=64)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'hash_arquivo')},
            },
        ),
    ]
