# Generated by Django 6.0.7 on 2026-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metafinanceira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='pago',
        ),
    ]
