# Generated by Django 6.0.7 on 2026-08-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contapagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_recebimento', models.DateField()),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Compras', 'Compras'), ('Salário', 'Salário'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('recebida', models.BooleanField(default=False)),
                ('recorrente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transacao_gerada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_origem_receber', to='core.transacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_recebimento'],
            },
        ),
    ]
